volumes:
  pg_data:
  static:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  
  backend:
    image: goodyear110/taski_backend
    env_file: .env
    volumes:
      - static:/backend_static
    depends_on:
      - db
  
  frontend:
    image: goodyear110/taski_frontend
    env_file: .env
    volumes:
      - static:/frontend_static
    command: cp -r /app/build/. /frontend_static
  
  gateway:
    image: goodyear110/taski_gateway
    ports:
      - 8000:80
    volumes:
      - static:/staticfiles
